import { IsEmail, IsNotEmpty, IsOptional, IsString, MaxLength, IsEnum } from 'class-validator';
import { ClubRole } from '../../common/rbac/roles';

export class CreateClubUserDto {
  @IsEmail()
  @IsNotEmpty()
  email!: string;

  @IsOptional()
  @IsString()
  @MaxLength(120)
  displayName?: string;

  @IsEnum(ClubRole)
  @IsNotEmpty()
  role!: ClubRole;

  // Password is auto-generated by backend
}

